version: '3'
services:
  sql:
    container_name: sql
    image: postgres:14.1-alpine
    user: root
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=temporaryPostgresPw123!
      - POSTGRES_DB=PiCamHomeSecurity
    network_mode: host
    volumes: 
      - ../../data/postgres/db:/var/lib/postgresql/data
      - ../../data/postgres/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  website:
    container_name: picam-home-security-website
    image: picam-home-security-website
    depends_on:
      - "sql"
    restart: unless-stopped
    network_mode: host
  nginx-rtmp:
    container_name: nginx-rtmp
    image: alfg/nginx-rtmp
    depends_on:
      - "website"
    restart: unless-stopped
    ports:
      - "1935:1935"
      - "8081:81"
    volumes:
      - ./nginx-rtmp/nginx.conf:/etc/nginx/nginx.conf.template